Repository ponylang/changelog-bot-action, pull requests merged in 2020-08, with the labels that each got.

#24 Retry push on failure
  .github/workflows/pr.yml
  Dockerfile
  entrypoint.py
  entrypoint.sh
Labels: changelog - added

#29 Turn on branch.autorebasesetup when pushing/pulling
  entrypoint.py
Labels: changelog - changed

#31 Fix broken push retries
  .release-notes/correct-repush.md
  entrypoint.py
Labels: changelog - fixed

#32 Fix failure when attempting push retries
  .release-notes/another-push-fix.md
  entrypoint.py
Labels: changelog - fixed
